[package]
name = "chat_rs"
version = "0.1.11"
edition = "2024"
description = "A simple chat server and client written in Rust"

[dependencies]
colored = "3.0.0"
toml = "0.8.21"
serde = {version = "1.0.218", features = ["derive"]} 
serde_json = "1.0"